baseURL = 'http://example.org/'
title = 'Dew Blog'
theme = 'hyde'
asCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[taxonomies]
tag = "tags"

[permalinks]
post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"


[params]
author = "Jacob Shore"                # You can also set author in post front matter individually
description = "The musings of Jacob Shore."
defaultTheme = "auto"              # default theme when first visit (auto|dark|light)



mainSections = ["post"]

