baseURL = 'http://example.org/'
title = 'Dew Blog'
theme = 'hugo-theme-stack'
disqusShortname = "dew-blog"

# [comments]
# enabled = true
# provider = "disqus"

# [comments.disqusjs]
# shortname = "dew-blog"

[colorScheme]
toggle = false

[params]
author = "Jacob Shore"                # You can also set author in post front matter individually
description = "The musings of Jacob Shore."
defaultTheme = "auto"              # default theme when first visit (auto|dark|light)
featuredImageField = "image"

[params]
author = "Jacob Shore"                # You can also set author in post front matter individually
description = "The musings of Jacob Shore."
defaultTheme = "auto"              # default theme when first visit (auto|dark|light)
featuredImageField = "image"
[params.comments]
enabled = true
provider = "disqus"

[params.comments.disqusjs]
shortname = "dew-blog"
mainSections = ["post"]

mainSections = ["post"]
[[cover]]
enabled = true


[goldmark.renderer]
unsafe = false

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

